#Github Actions workflow for CI/CD pipelines

name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1-5' # Runs every weekday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run script
      run: |
        echo "Running CI/CD pipeline..."
    - name: Maven Build
      run: |
        mvn clean install

  Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run tests
      run: |
        echo "Running tests..."
        mvn test
    - name: Checkstyle
      run: |
        echo "Running Checkstyle..."
        mvn checkstyle:checkstyle
