#Github Actions workflow for CI/CD pipelines

name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1-5' # Runs every weekday at 00:00 UTC

env:
  ECR_REPOSITORY: vprofile-appimage

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run script
      run: |
        echo "Running CI/CD pipeline..."
    - name: Maven Build
      run: |
        mvn clean install
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vprofile
        path: target/*.war
    - name: Notify if Build Fails
      if: failure()
      run: |
        echo "Build failed! Please check the logs for details."

  Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run tests
      if: github.ref == 'refs/heads/main'  
      run: |
        echo "Running tests..."
        mvn test
    - name: Checkstyle
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Running Checkstyle..."
        mvn checkstyle:checkstyle
    - name: Skipping tests for non-main branches
      if: github.ref != 'refs/heads/main'
      run: |
        echo "Skipping tests for non-main branch."

  Security-Scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Trivy Security Scan
      if: github.ref == 'refs/heads/main'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'json'
        exit-code: '0'
        vulnerabilities-type: 'os,library'
        output: 'trivy-report.json'

    - name: Upload Trivy Report
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results
        path: trivy-report.json
       
    - name: Skipping security scan for non-main branches
      if: github.ref != 'refs/heads/main'
      run: |
        echo "Skipping security scan for non-main branch."


   BUILD_AND_PUBLISH:
     name: Build and Publish
     runs-on: ubuntu-latest
     needs: [build, Test, Security-Scan]
     environment:
       name: production
     if: github.ref == 'refs/heads/main'
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ vars.AWS_REGION }}
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build tag and Push Docker image to Amazon ECR
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
         IMAGE_TAG: ${{ github.sha }}
       run: |
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG